name: CI to Build and Deploy to Heroku

on:
  push:
    branches:
      - main
    tags:
      - v\d+\.\d+\d+

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish and Deploy
    runs-on: ubuntu-latest
    env:
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}

    steps:
      - name: Set ENV
        run: |-
          if  [ ${GITHUB_REF##*/} = "main" ];  then
            echo  "ENV=staging" >>  $GITHUB_ENV
            echo  "APP_NAME=storybooks-staging" >>  $GITHUB_ENV
          else
            echo  "ENV=prod"  >>  $GITHUB_ENV
            echo  "APP_NAME=storybooks"  >>  $GITHUB_ENV
          fi
      - name: test ENV
        run: |-
          echo ${GITHUB_REF}
          echo ${GITHUB_REF##*/}
      - name: Checkout
        uses: actions/checkout@v2
      ### Push to multi-registries
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Heroku Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ env.HEROKU_TOKEN }}
      # Build the Docker image
      - name: Build
        run: |-
          make build
      - name: Publish to DockerHub
        run: |-
          DOCKERHUB_USERNAME=${{ env.REGISTRY_USERNAME }} make push
      - name: Publish to Heroku
        run: |-
          DOCKERHUB_USERNAME=${{ env.REGISTRY_USERNAME }} APP_NAME=${{ env.APP_NAME }} make heroku-push
      - name: Deploy
        run: |-
          HEROKU_API_KEY=${{ env.HEROKU_TOKEN }} APP_NAME=${{ env.APP_NAME }} make run-deploy
      - name: Check App Health
        run: |-
          make check-app-health
